#url: "http://projects.flo.by/node-libspotify"
pygments: true
exclude: [/bin, Gemfile, Gemfile.lock]
markdown: redcarpet
#markdown: kramdown
#markdown: rdiscount
permalink: pretty
paginate: 5
project: node-libspotify
project_image: /images/node-libspotify-icon.png
menu_item: projects
title: node-libspotify
submenu:
    - slug: home
      name: Home
      link: '/'

    - slug: download
      name: Download
      link: '/download'

    - slug: tuto
      name: Quick Start
      link: '/quick-start'

    - slug: readme
      name: Read me
      link: '/readme'

kramdown:
  entity_output: symbolic
rdiscount:
  entity_output: symbolic
redcarpet:
  entity_output: symbolic
