url: "http://projects.flo.by/"
base_url:"http://projects.flo.by/node-libspotify/"
pygments: true
exclude: [/bin, Gemfile, Gemfile.lock]
markdown: kramdown
#markdown: rdiscount
permalink: pretty
paginate: 5

kramdown:
  entity_output: symbolic
rdiscount:
  entity_output: symbolic
