url: "http://projects.flo.by/node-libspotify/"
pygments: true
exclude: [/bin, Gemfile, Gemfile.lock]
markdown: redcarpet
#markdown: kramdown
#markdown: rdiscount
permalink: pretty
paginate: 5
project: node-libspotify
menu_item: projects

kramdown:
  entity_output: symbolic
rdiscount:
  entity_output: symbolic
redcarpet:
  entity_output: symbolic
